name: Coveo Dependency Reviewer

on:
  workflow_call:
    inputs:
      public:
        required: true
        type: boolean
        default: false
      distributed:
        required: true
        type: boolean
        default: true

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scan target
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Checkout licenses
        uses:  actions/checkout@v3
        with:
          repository: coveo/dependency-allowed-licenses
          path: coveo-dependency-allowed-licenses
          ref: a87f5a959448264a1b6460b35320b18bd113d90f

      - name: Select configuration
        id: select-config
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        env:
          INPUTS: ${{ toJSON(inputs) }}
        with:
          result-encoding: string
          script: |
            const inputs = JSON.parse(process.env.INPUTS)
            if (inputs.public) {
              return 'public.yml'
            }
            if (!inputs.public && inputs.distributed) {
              return 'private-distributed.yml'
            }
            if (!inputs.public && !inputs.distributed) {
              return 'private-undistributed.yml'
            }

            core.setFailure(`Could not determine configuration for inputs: ${inputs}`)

      - name: Scan
        uses: actions/dependency-review-action@f46c48ed6d4f1227fb2d9ea62bf6bcbed315589e # v3
        with:
          comment-summary-in-pr: true
          fail-on-severity: high
          config-file: ./coveo-dependency-allowed-licenses/${{ steps.select-config.outputs.result }}
