name: 'Maven Dependency Review'

on:
  workflow_call:
    inputs:
      runs-on:
        description: |
          The type of machine to run the job on. Must be provided as a stringified list (e.g. `runs-on: '["ubuntu-latest","self-hosted"]'`)
        required: true
        type: string

      # Dependency Submission inputs
      directory:
        description: 'The directory that contains the pom.xml that will be used to generate the dependency graph from'
        default: '.'
        required: false
        type: string
      mvn-version:
        description: |
          The Maven version used for the execution. You can specify minor or patch version (3.9 or 3.9.1). Default : 3.9
        required: false
        type: number
        default: 3.9
      jdk-version:
        description: |
          The JDK version to use for the build.
        required: true
        type: number
      mvn-additional-arguments:
        description: |
          The additional arguments to pass to the Maven invocation. You can use this to specify a custom profile for example.

          If you wish to exclude certain modules from the scan, pass: -Dexcludes=groupId:artifactId:type:classifier

        required: false
        type: string

      # Dependency Reviewer inputs
      comment-summary-in-pr:
        description: Determines if the summary is posted as a comment in the PR itself. Setting this to `always` or `on-failure` requires you to give the workflow the write permissions for pull-requests
        required: false
        default: on-failure
        type: string
      base-ref:
        description: Provide custom git references for the git base
        required: false
        default: ${{ github.event.pull_request.base.sha }}
        type: string
      head-ref:
        description: Provide custom git references for the git head
        required: false
        default: ${{ github.event.pull_request.head.sha }}
        type: string
      fail-on-severity:
        description: Defines the threshold for the level of severity. The action will fail on any pull requests that introduce vulnerabilities of the specified severity level or higher.
        required: false
        default: high
        type: string
      warn-on-openssf-scorecard-level:
        description: Numeric threshold for the OpenSSF Scorecard score. If the score is below this threshold, the action will warn you.
        required: false
        type: number
        default: 3

permissions: { }

jobs:
  get-repository-properties:
    name: Get Properties
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      is_distributed: ${{ steps.get-properties.outputs.is_distributed }}
      is_public: ${{ steps.get-properties.outputs.is_public }}

    steps:
      - name: Get Properties
        uses: actions/github-script@v7
        id: get-properties
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const response = await github.request('GET /repos/{owner}/{repo}/properties/values', {
              owner: owner,
              repo: repo
            });
            console.log(response.data);
            const distributedProperty = response.data.find(prop => prop.property_name === 'is_distributed');
            const distributedValue = distributedProperty ? distributedProperty.value : 'true';
            core.setOutput('is_distributed', distributedValue);

            const repoDetails = await github.request('GET /repos/{owner}/{repo}', {
              owner: owner,
              repo: repo
            });
            const isPublic = repoDetails.data.private ? 'false' : 'true';
            console.log(`Is this a public repo? ${isPublic}`);
            core.setOutput('is_public', isPublic);

  validate-outputs:
    needs: get-repository-properties
    name: Validate Outputs
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Validate Outputs
        run: |
          echo "Is Distributed: ${{ needs.get-repository-properties.outputs.is_distributed }}"
          echo "Is Public: ${{ needs.get-repository-properties.outputs.is_public }}"

  submit-dependencies:
    needs: get-repository-properties
    name: Submit dependencies
    uses: ./.github/workflows/java-maven-openjdk-dependency-submission.yml

    permissions:
      contents: write

    with:
      runs-on: ${{ inputs.runs-on }}
      directory: ${{ inputs.directory }}
      mvn-version: ${{ inputs.mvn-version }}
      jdk-version: ${{ inputs.jdk-version }}
      mvn-additional-arguments: ${{ inputs.mvn-additional-arguments }}

  dependency-review:
    needs: submit-dependencies
    name: Dependency Review
    uses: ./.github/workflows/dependency-review.yml

    permissions:
      contents: read
      pull-requests: write

    with:
      runs-on: ${{ inputs.runs-on }}
      public: ${{ needs.get-repository-properties.outputs.is_public }}
      distributed: ${{ needs.get-repository-properties.outputs.is_distributed }}
      comment-summary-in-pr: ${{ inputs.comment-summary-in-pr }}
      base-ref: ${{ inputs.base-ref }}
      head-ref: ${{ inputs.head-ref }}
      fail-on-severity: ${{ inputs.fail-on-severity }}
      retry-on-snapshot-warnings: true
      retry-on-snapshot-warnings-timeout: 120
      warn-on-openssf-scorecard-level: ${{ inputs.warn-on-openssf-scorecard-level }}
