name: 'Submit Maven Dependencies Snapshot'

on:
  workflow_call:
    inputs:
      runs-on:
        description: |
          The type of machine to run the job on. Must be provided as a stringified list (e.g. `runs-on: '["ubuntu-latest","self-hosted"]'`)
        required: true
        type: string
      directory:
        description: 'The directory that contains the pom.xml that will be used to generate the dependency graph from'
        default: '.'
        required: false
        type: string

permissions: { }

jobs:
  submit-dependencies:
    name: Submit dependencies
    uses: coveo/public-actions/.github/workflows/java-maven-openjdk-dependency-submission.yml@main
    with:
      runs-on: ${{ inputs.runs-on }}
      directory: ${{ inputs.directory }}
      jdk-version: 11
    permissions:
      contents: write
