name: Test Coveo Dependency Reviewer

on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    strategy:
      matrix:
        public: [true, false]
        distributed: [true, false]
        comment-summary-in-pr: [true, false]
      fail-fast: false

    uses: ./.github/workflows/dependency-review.yml
    with:
      public: ${{ matrix.public }}
      distributed: ${{ matrix.distributed }}
      comment-summary-in-pr: ${{ matrix.comment-summary-in-pr }}
      runs-on: '["ubuntu-latest"]'
