name: Test Coveo Dependency Reviewer

on: pull_request

permissions: { }

jobs:
  test:
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        warn-on-openssf-scorecard-level: [ 5, 8 ]
      fail-fast: false

    uses: ./.github/workflows/dependency-review-v3.yml
    with:
      warn-on-openssf-scorecard-level: ${{ matrix.warn-on-openssf-scorecard-level }}
      runs-on: '["ubuntu-latest"]'
