name: Test Coveo Dependency Reviewer

on: pull_request

permissions: { }

jobs:
  test:
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        public: [ true, false ]
        distributed: [ true, false ]
        comment-summary-in-pr: [ true, false ]
      fail-fast: false

    uses: ./.github/workflows/dependency-review.yml
    with:
      public: ${{ matrix.public }}
      distributed: ${{ matrix.distributed }}
      comment-summary-in-pr: ${{ matrix.comment-summary-in-pr }}
      runs-on: '["ubuntu-latest"]'

  test_v2:
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        warn-on-openssf-scorecard-level: [ 5, 8 ]
        comment-summary-in-pr: [ true, false ]
      fail-fast: false

    uses: ./.github/workflows/dependency-review-v2.yml
    with:
      warn-on-openssf-scorecard-level: ${{ matrix.warn-on-openssf-scorecard-level }}
      comment-summary-in-pr: ${{ matrix.comment-summary-in-pr }}
      runs-on: '["ubuntu-latest"]'

  test_v3:
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        warn-on-openssf-scorecard-level: [ 5, 8 ]
        comment-summary-in-pr: [ true, false ]
      fail-fast: false

    uses: ./.github/workflows/dependency-review-v3.yml
    with:
      warn-on-openssf-scorecard-level: ${{ matrix.warn-on-openssf-scorecard-level }}
      comment-summary-in-pr: ${{ matrix.comment-summary-in-pr }}
      runs-on: '["ubuntu-latest"]'
